<?php
/**
 * @var \App\View\AppView $this
 * @var array $previewData
 */
$this->assign('title', __('Preview Import Data'));
?>
<div class="freshInvoices form content">
    <style>
        .preview-header {
            background: linear-gradient(135deg, #1e7e34 0%, #28a745 100%);
            color: white;
            padding: 2rem;
            border-radius: 10px 10px 0 0;
            margin-bottom: 0;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .preview-container {
            background: white;
            border-radius: 0 0 10px 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .preview-actions {
            padding: 2rem;
            background: #f8f9fa;
            border-top: 3px solid #28a745;
        }
        .preview-table-wrapper {
            overflow-x: auto;
            max-height: 600px;
            overflow-y: auto;
        }
        .preview-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.9rem;
        }
        .preview-table thead {
            position: sticky;
            top: 0;
            background: #495057;
            color: white;
            z-index: 10;
        }
        .preview-table th {
            padding: 1rem 0.75rem;
            text-align: left;
            font-weight: 600;
            border-bottom: 2px solid #28a745;
            white-space: nowrap;
        }
        .preview-table td {
            padding: 0.75rem;
            border-bottom: 1px solid #dee2e6;
            vertical-align: top;
        }
        .preview-table tbody tr:hover {
            background: #f8f9fa;
        }
        .preview-table tbody tr:nth-child(even) {
            background: #f8f9fa;
        }
        .preview-table tbody tr:nth-child(even):hover {
            background: #e9ecef;
        }
        .row-number {
            font-weight: bold;
            color: #6c757d;
            background: #e9ecef !important;
            text-align: center;
        }
        .empty-cell {
            color: #6c757d;
            font-style: italic;
        }
        .auto-gen {
            color: #28a745;
            font-style: italic;
            font-weight: 500;
        }
        .stat-badge {
            display: inline-block;
            padding: 0.5rem 1rem;
            background: rgba(255,255,255,0.2);
            border-radius: 20px;
            margin-right: 1rem;
            font-size: 1.1rem;
        }
        .warning-box {
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 1rem;
            margin: 1rem 0;
        }
        .btn-confirm {
            background: linear-gradient(135deg, #1e7e34 0%, #28a745 100%);
            color: white;
            padding: 1rem 2rem;
            font-size: 1.1rem;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: all 0.3s;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .btn-confirm:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 12px rgba(0,0,0,0.15);
        }
        .btn-cancel {
            background: #6c757d;
            color: white;
            padding: 1rem 2rem;
            font-size: 1.1rem;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: all 0.3s;
            margin-left: 1rem;
        }
        .btn-cancel:hover {
            background: #5a6268;
        }
    </style>

    <div class="preview-header">
        <h2><i class="fas fa-eye"></i> Preview Import Data</h2>
        <p style="margin: 0.5rem 0 0 0; opacity: 0.9;">
            Review the parsed data below. Verify all information is correct before importing.
        </p>
        <div style="margin-top: 1rem;">
            <span class="stat-badge">
                <i class="fas fa-file-invoice"></i> <strong><?= count($previewData) ?></strong> invoices
            </span>
        </div>
    </div>

    <div class="preview-container">
        <div class="warning-box">
            <i class="fas fa-info-circle"></i> <strong>Please verify:</strong>
            <ul style="margin: 0.5rem 0 0 0; padding-left: 1.5rem;">
                <li>All client names, products, and vessels match your records</li>
                <li>Quantities and prices are correct</li>
                <li>Invoice numbers will be auto-generated by the system</li>
                <li>Contract IDs match existing contracts (new ones will be created if needed)</li>
            </ul>
        </div>

        <div class="preview-table-wrapper">
            <table class="preview-table">
                <thead>
                    <tr>
                        <th class="row-number">#</th>
                        <th>Client Name</th>
                        <th>Product Name</th>
                        <th>Contract ID</th>
                        <th>Vessel Name</th>
                        <th>BL Number</th>
                        <th>Quantity (MT)</th>
                        <th>Unit Price</th>
                        <th>Payment %</th>
                        <th>SGC Account ID</th>
                        <th>Notes</th>
                        <th>Type</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($previewData as $index => $row): ?>
                        <tr>
                            <td class="row-number"><?= $index + 1 ?></td>
                            <td><?= h($row['Client Name']) ?></td>
                            <td><?= h($row['Product Name']) ?></td>
                            <td><?= h($row['Contract ID']) ?></td>
                            <td><?= h($row['Vessel Name']) ?></td>
                            <td><?= h($row['BL Number']) ?></td>
                            <td style="text-align: right;"><?= h(number_format($row['Quantity(MT)'], 2)) ?></td>
                            <td style="text-align: right;"><?= h(number_format($row['Unit Price'], 2)) ?></td>
                            <td style="text-align: right;"><?= h($row['Payment %']) ?>%</td>
                            <td><?= h($row['SGC Account ID'] ?? '') ?: '<span class="empty-cell">Not specified</span>' ?></td>
                            <td><?= h($row['Notes'] ?? '') ?: '<span class="empty-cell">No notes</span>' ?></td>
                            <td><?= h($row['BULK/BAG'] ?? 'BULK') ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <div class="preview-actions">
            <?= $this->Form->create(null, ['url' => ['action' => 'bulkUpload']]) ?>
            <?= $this->Form->hidden('confirm_import', ['value' => '1']) ?>
            <?= $this->Form->hidden('preview_data', ['value' => json_encode($previewData)]) ?>
            
            <div style="text-align: center;">
                <button type="submit" class="btn-confirm">
                    <i class="fas fa-check-circle"></i> Confirm & Import <?= count($previewData) ?> Invoices
                </button>
                
                <?= $this->Html->link(
                    '<i class="fas fa-times-circle"></i> Cancel & Go Back',
                    ['action' => 'bulkUpload'],
                    ['class' => 'btn-cancel', 'escape' => false]
                ) ?>
            </div>
            
            <?= $this->Form->end() ?>
            
            <p style="text-align: center; margin-top: 1rem; color: #6c757d; font-size: 0.9rem;">
                <i class="fas fa-info-circle"></i> Missing clients, products, vessels, and contracts will be created automatically
            </p>
        </div>
    </div>
</div>
