<?php
return array (
  'app_name' => 'Treasury Invoicing App',
  'company_name' => 'Your Company Name',
  'company_address' => '',
  'company_phone' => '',
  'company_email' => '',
  'company_website' => '',
  'tax_id' => '',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'date_format' => 'Y-m-d',
  'timezone' => 'UTC',
  'items_per_page' => 25,
  'enable_email_notifications' => true,
  'enable_audit_log' => true,
  'session_timeout' => 30,
  'teams_enabled' => true,
  'teams_team_id' => '',
  'teams_channel_id' => '',
  'power_automate_enabled' => true,
  'power_automate_flow_url' => '',
  'power_automate_secret' => '',
  'pdf_logo' => '',
);
